# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/cons.xdc

# IP: ip/axi_bus/axi_bus.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bus || ORIG_REF_NAME==axi_bus} -quiet] -quiet

# IP: ip/mr_bram/mr_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mr_bram || ORIG_REF_NAME==mr_bram} -quiet] -quiet
